apps/index/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^callback$', views.callback, name='callback'),
    url(r'^logout$', views.logout, name='logout'),
]

apps/minono/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^index$', views.MinonoIndexView.as_view(), name='index'),
    url(r'^point$', views.MinonoPointView.as_view(), name='point')
]

apps/store/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views
from django.contrib.auth.forms import AuthenticationForm

urlpatterns = [
    url(r'^$', views.StoreIndexView.as_view(), name='index'),
    url(r'^regist$', views.StoreUserRegistView.as_view(), name='regist'),
    url(r'^login/$',
        auth_views.login,
        {'template_name': 'store/login.html',
         'authentication_form': AuthenticationForm,
         'extra_context': {'title': '店舗ログイン'}},
        name='login'),
    url(r'^logout/$',
        # ログアウト後ログインページへリダイレクト
        auth_views.logout_then_login,
        name='logout'),
]

trunk_minokyon/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^minono/', include('minono.urls', namespace='minono')),
    url(r'', include('index.urls', namespace='index')),
    url(r'store/', include('store.urls', namespace='store')),
]

apps/index/models.py
from django.db import models

# Create your models here.

apps/store/models.py
from django.db import models
from django.contrib.auth import get_user_model


class StoreLog(models.Model):
    store_user = models.ForeignKey(
        get_user_model(),
        related_name='logs')
    username = models.CharField(max_length=256)
    geek_rank = models.CharField(max_length=256)
    kind = models.CharField(max_length=256)
    created_at = models.CharField(max_length=256)

apps/index/views.py
import math

from django.shortcuts import render, redirect
from django.views import generic

from .github_auth import github
from . import utils


# 描画全部この子がやる
class IndexView(generic.TemplateView):
    template_name = 'index/index.html'

    def get(self, request, *args, **kwargs):
        if 'username' not in request.session:
            context = dict(authorize_url=github.get_authorize_url())
            return render(request, 'index/welcome.html', context)
        else:
            self.username = request.session['username']
            self.contribution = utils.get_7days_user_contribution(self.username)
            request.session['geek_rank_name'] = self.geek_rank_name
            utils.create_qrcode_images(request)
            return super().get(request, *args, **kwargs)

    # context
    @property
    def geek_point(self):
        return round(self.contribution ** math.log(530000, 70))

    @property
    def geek_rank(self):
        if self.geek_point == 1:
            return 0  # 0
        elif self.geek_point < 5000:
            return 1  # 1 - 15
        elif self.geek_point < 100000:
            return 2  # 16 - 40
        elif self.geek_point < 530000:
            return 3  # 40 - 69
        else:
            return 4  # 70 -

    @property
    def geek_rank_name(self):
        if self.geek_rank == 0:
            return 'ぎーくやあらへん'
        elif self.geek_rank == 1:
            return 'しょしんしゃぎーく'
        elif self.geek_rank == 2:
            return 'まあまあぎーく'
        elif self.geek_rank == 3:
            return 'いっちょまえぎーく'
        elif self.geek_rank == 4:
            return 'どえらいぎーく！！'


# github から返ってきたコードを用いて、
# access トークン取得
# ユーザー名を セッション に保存
def callback(request):
    request.session['username'] = utils.get_github_username(request)
    return redirect('index:index')


def logout(request):
    request.session.clear()
    return redirect('index:index')

apps/minono/views.py
from django.views import generic


class MinonoIndexView(generic.TemplateView):
    template_name = 'minono/minono.html'


class MinonoPointView(generic.TemplateView):
    template_name = 'minono/point.html'

apps/store/views.py
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.core.urlresolvers import reverse_lazy
from django.views import generic
from django.contrib.auth.forms import UserCreationForm


from .models import StoreLog


class StoreIndexView(generic.TemplateView):
    template_name = 'store/index.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):

        if 'username' in request.GET:
            s = StoreLog(
                store_user=request.user,
                username=request.GET.get('username'),
                kind=request.GET.get('kind'),
                geek_rank=request.GET.get('rank'),
                created_at=request.GET.get('date'))
            s.save()
            return redirect('store:index')

        return super().get(request, *args, **kwargs)


class StoreUserRegistView(generic.CreateView):
    template_name = 'store/regist.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('store:index')

templates/base.html
{% extends 'html_head.html' %}

{% block body %}

  <main class="main">   <!-- 全体 -->
    {% block content %}{% endblock %}
  </main>

{% endblock body %}

templates/html_head.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
  {% block head %}
    <head>
      <meta charset="UTF-8">
      <title>オーサカGEEKER</title>
      <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
      <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
      <script src="{% static 'js/bootstrap.min.js' %}"></script>
    </head>
  {% endblock %}

  <body>
    {% block body %}{% endblock %}

  </body>

</html>

templates/index/index.html
{% extends 'base.html' %}

{% block content %}
  <div>{{ view.username }} のギークランク</div>
  <div class="c-container--main">
    <div class="c-rank">
      <img class="c-bg c-bg__rank" src="/static/img/rank_{{ view.geek_rank }}.png"></img>
      {{ view.geek_rank_name }}
      <span class="c-rank--point">
        <a data-toggle="modal" data-target="#RankDescriptionModal"><i class="fa fa-fw fa-question-circle-o" aria-hidden="true"></i></a>
      </span>

    </div>
    <div class="c-rank--point">
      ギークポイント: {{ view.geek_point }}
    </div>
  </div>



  <div class="c-container--list">


    <div class="c-list">

      <div class="c-list--title">
        ギーカーチケット<a data-toggle="modal" data-target="#GeekerRankDescriptionModal"><i class="fa fa-fw fa-question-circle-o" aria-hidden="true"></i></a>
      </div>

      <a data-toggle="modal" data-target="#KonamonModal">
        <div class="c-list--item">

          <p class="ribbon4 c-list--item__available"><i class="fa fa-fw fa-circle-o" aria-hidden="true"></i>コナモン</p>

        </div>
      </a>

      <a data-toggle="modal" data-target="#OmoroiModal">
        <div class="c-list--item">

          <p class="ribbon4 c-list--item__available"><i class="fa fa-fw fa-circle-o" aria-hidden="true"></i>オモロイ</p>

        </div>
      </a>
      {% if view.geek_rank == 0 or view.geek_rank == 1 %}
        <div class="c-list--item">
          <p class="ribbon4 c-list--item__unavailable"><i class="fa fa-fw fa-times" aria-hidden="true"></i>アツマロ</p>
        </div>
      {% else %}
        <a data-toggle="modal" data-target="#AtsumaroModal">
          <div class="c-list--item">
            <p class="ribbon4 c-list--item__available"><i class="fa fa-fw fa-circle-o" aria-hidden="true"></i>アツマロ</p>
          </div>
        </a>
      {% endif %}

    </div>

  </div>

  <!-- モーダル -->

  <div class="modal fade" id="RankDescriptionModal">
    <div class="modal-dialog modal-margin">

      <div class="modal-content">
        <div class="modal-header" style="font-size: 8vw">
          ギークランクとは
        </div>
        <div class="modal-body">
          あんさんが github で草生やせば生やすほどギークポイントが増えおって、ぎょーさんなったらギークランクがあがるんや。<br/>
          ギークランクがあがると、大阪での暮らしがどんどん便利にになるさかい、きばりや!<br/>
          あ、そうそう。草生やせば生やすほどゆうても、最近一週間分だけを反映しとるでな、休まずに草生やしたってや!
          <img style="width: 100%;" src="/static/img/geek_rank.png"></img>
        </div>


      </div>

    </div>
  </div>

  <div class="modal fade" id="GeekerRankDescriptionModal">    <!-- ギーカーランク -->
    <div class="modal-dialog modal-margin">

      <div class="modal-content">
        <div class="modal-header" style="font-size: 8vw">
          ギーカーチケットとは
        </div>
        <div class="modal-body">
          ギークランクに応じて、色んなオトクなサービスに利用できるチケットが使えるで <br/><br/>
          <li>コナモン： 大阪のウマいコナモンがお得に食べられるで!</li>
          <li>オモロイ： 日変わりのオモロイ大阪の楽しみを提供するで</li>
          <li>アツマレ： ギークポイント 5000 以上でタダで使えるコワーキングスペースや!</li>
        </div>


      </div>

    </div>
  </div>


  <div class="modal fade" id="KonamonModal">
    <div class="modal-dialog modal-margin">
      <div class="modal-content">
        <div class="modal-header" style="font-size: 10vw">
          今日のコナモン
        </div>
        <div class="modal-body">
          <img style="width: 10vw" src="/static/img/rank_{{ view.geek_rank }}.png"></img>
          <span style="font-size: 6vw">{{ view.geek_rank_name }} </span><span class="c-font-sm">のあんさんは</span>
          <br/><br/>
          <div style="font-size: 6vw">
            {% if view.geek_rank == 0 %}
              なんもないで。
            {% elif view.geek_rank == 1 %}
              たこやき50円引き!
            {% elif view.geek_rank == 2 %}
              たこやき1個タダ!
            {% elif view.geek_rank == 3 %}
              たこやき3個タダ!
            {% elif view.geek_rank == 4 %}
              たこやき30分食べ放題!
            {% endif %}
            {% if view.geek_rank %}            
              <img style='height: 30vh;' src="/static/img/qrcodes/{{ view.username }}_コナモン.png"/>
            {% endif %}
          </div>
          <br/>

          <ul class="c-list-unstyled">
            <li>おみせ：みのりたこやき</li>
            <li>ばしょ：<a href="#">北区2018丁目3番地9</a></li>
          </ul>

          <hr/>
          <hr/>

          <div>あしたは... おこのみやき!!</div>

          <hr/>
          <hr/>
          <div style="font-size: 2vw">
            {% if view.geek_rank == 0 %}
              (ちなみに、次のギークランクやと、たこやき50円引き やってんで)
            {% elif view.geek_rank == 1 %}
              (ちなみに、次のギークランクやと、たこやき1個タダ やってんで)
            {% elif view.geek_rank == 2 %}
              (ちなみに、次のギークランクやと、たこやき3個タダ やってんで)
            {% elif view.geek_rank == 3 %}
              (ちなみに、次のギークランクやと、たこやき30分食べ放題 やってんで)
            {% elif view.geek_rank == 4 %}

            {% endif %}
          </div>
        </div>


      </div>

    </div>
  </div>

  <div class="modal fade" id="OmoroiModal">
    <div class="modal-dialog modal-margin">
      <div class="modal-content">
        <div class="modal-header" style="font-size: 10vw">
          今日のオモロイ
        </div>
        <div class="modal-body">
          <img style="width: 10vw" src="/static/img/rank_{{ view.geek_rank }}.png"></img>
          <span style="font-size: 6vw">{{ view.geek_rank_name }} </span><span class="c-font-sm">のあんさんは</span>
          <br/><br/>
          <div style="font-size: 6vw">
            {% if view.geek_rank == 0 %}
              まだなんもないで。
            {% elif view.geek_rank == 1 %}
              通天閣入場料300円引き!
            {% elif view.geek_rank == 2 %}
              海遊館入館料半額!
            {% elif view.geek_rank == 3 %}
              海遊館1人分タダ!
            {% elif view.geek_rank == 4 %}
              海遊館2人分タダ!
            {% endif %}
            {% if view.geek_rank %}            
              <img style='height: 30vh;' src="/static/img/qrcodes/{{ view.username }}_オモロイ.png"/>
            {% endif %}
          </div>
          <br/>

          <ul class="c-list-unstyled">
            <li>おみせ：海遊館</li>
            <li>ばしょ：<a href="#">港区海岸通1丁目1−10</a></li>
          </ul>

          <hr/>
          <hr/>

          <div>あしたは... USJ!!</div>

          <hr/>
          <hr/>
          <div style="font-size: 2vw">
            {% if view.geek_rank == 0 %}
              (ちなみに、次のギークランクやと、海遊館300円引き やってんで)
            {% elif view.geek_rank == 1 %}
              (ちなみに、次のギークランクやと、海遊館半額 やってんで)
            {% elif view.geek_rank == 2 %}
              (ちなみに、次のギークランクやと、海遊館タダ やってんで)
            {% elif view.geek_rank == 3 %}
              (ちなみに、次のギークランクやと、海遊館2人分タダ やってんで)
            {% elif view.geek_rank == 4 %}

            {% endif %}
          </div>
        </div>


      </div>

    </div>
  </div>

  <div class="modal fade" id="AtsumaroModal">
    <div class="modal-dialog modal-margin">
      <div class="modal-content">
        <div class="modal-header" style="font-size: 10vw">
          今日のアツマロ
        </div>
        <div class="modal-body">
          <img style="width: 10vw" src="/static/img/rank_{{ view.geek_rank }}.png"></img>
          <span style="font-size: 6vw">{{ view.geek_rank_name }} </span><span class="c-font-sm">のあんさんは</span>
          <br/><br/>
          <div style="font-size: 6vw">
            {% if view.geek_rank == 0 %}
              まだなんもないで。
            {% elif view.geek_rank == 1 %}
              まだなんもないで。
            {% elif view.geek_rank == 2 %}
              営業時間内利用&ドリンク1杯
            {% elif view.geek_rank == 3 %}
              営業時間内利用&ドリンク飲み放題
            {% elif view.geek_rank == 4 %}
              24時間無料&ドリンク飲み放題
            {% endif %}
            {% if view.geek_rank %}
              <img style='height: 30vh;' src="/static/img/qrcodes/{{ view.username }}_アツマロ.png"/>
            {% endif %}

          </div>
          <br/>

          <ul class="c-list-unstyled">
            <li>なまえ：さくらインターネット さん</li>
            <li>ばしょ：<a href="#">グランフロント大阪タワーA 35F</a></li>
          </ul>

          <hr/>
          <hr/>

          <div>あしたは... TRUNK さん!!</div>

          <hr/>
          <hr/>
          <div style="font-size: 2vw">
            {% if view.geek_rank == 0 %}
              (ちなみに、次の次のギークランクやと、営業時間内利用 & ドリンク1杯 やってんで)
            {% elif view.geek_rank == 1 %}
              (ちなみに、次のギークランクやと、営業時間内利用 & ドリンク1杯 やってんで)
            {% elif view.geek_rank == 2 %}
              (ちなみに、次のギークランクやと、営業時間内利用 & ドリンク飲み放題 やってんで)
            {% elif view.geek_rank == 3 %}
              (ちなみに、次のギークランクやと、24時間利用 & ドリンク飲み放題 やってんで)
            {% elif view.geek_rank == 4 %}

            {% endif %}
          </div>
        </div>


      </div>

    </div>
  </div>

{% endblock %}

templates/index/welcome.html
{% extends 'base.html' %}

{% block content %}
  <div class="c-container--lead">
    <div class="c-title" style="padding-top: 10vh">
      <img class="c-bg c-bg__top" src="/static/img/trunk_top.png"></img>

    </div>
  </div>

  <div class="c-container--btn">
    <a  href="{{ authorize_url }}" class="c-button">
      <div>使ってみよか！</div>
    </a>
  </div>

  <div class="c-container--intro">
    <p>オトクやさかい使ってみ!</p>
  </div>
  
{% endblock %}

templates/minono/minono.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>オーサカGEEKER</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
    <link href="../static/css/style.css" rel="stylesheet" type="text/css">
  </head>
  <body>
    <div class="main">   <!-- 全体 -->

      <div class="c-container--lead">
        <div class="c-title">
          <img class="c-bg c-bg__top" src="/static/img/trunk_top.png"></img>

        </div>
      </div>

      <div class="c-container--btn">
        <a href class="c-button">使ってみよか！</a>
      </div>

      <div class="c-container--intro">
        <p>ああああああああああああああ</p>
      </div>

    </div>

  </body>
</html>

templates/minono/point.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>オーサカGEEKER</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
    <link href="../static/css/style.css" rel="stylesheet" type="text/css">
  </head>
  <body>
    <div class="main">   <!-- 全体 -->

      <div class="c-container--main">
        <div class="c-rank">
          <img class="c-bg c-bg__rank" src="/static/img/rank_1.png"></img>
        </div>
        <div class="c-rank--name">
            どえらいぎーく！！
        </div>
      </div>

      <div class="c-container--list">
        <div class="c-list">

          <div class="c-list--item">
            <p class="ribbon4 c-list--item__available"><i class="fa fa-fw fa-circle-o" aria-hidden="true"></i>コナモン</p>
          </div>

          <div class="c-list--item">
            <p class="ribbon4 c-list--item__available"><i class="fa fa-fw fa-circle-o" aria-hidden="true"></i>お好み焼き食べよや</p>
          </div>

          <div class="c-list--item">
            <p class="ribbon4 c-list--item__unavailable"><i class="fa fa-fw fa-times" aria-hidden="true"></i>あああああああ</p>
          </div>

        </div>
      </div>


    </div>
  </body>
</html>

templates/store/index.html
{% extends 'base.html' %}

{% block content %}
  <div style="font-size: 3vw; padding: 3vw;">
    <div style='text-align: right'>
      <a href="{% url 'index:index' %}">サービストップへ</a>
      <a href="{% url 'store:logout' %}">ログアウト</a>
    </div>
    
    <div>店舗ユーザー名：{{ user }}</div>
    <div>利用ユーザー履歴</div>
    <table class="table" >
      <thead>
        <tr>
          <th style="text-align: center;">日付</th>
          <th style="text-align: center;">ユーザ名</th>
          <th style="text-align: center;">ギークランク</th>
          <th style="text-align: center;">サービス種類</th>
        </tr>
      </thead>
      <tbody>
        {% for data in user.logs.all %}
          <tr>
            <td>{{ data.created_at }}</td>
            <td>{{ data.username }}</td>
            <td>{{ data.geek_rank }}</td>
            <td>{{ data.kind }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

templates/store/login.html
{% extends 'base.html' %}

{% block content %}
  <div style="font-size: 5vw; padding: 5vw;">
    <div class="login-title">
      <ul class="list-inline">
        <li>店舗ログイン</li>
      </ul>
    </div>
    <div>
      <form action="{% url 'store:login' %}" method="POST">
        <div>
          <table style='margin: auto'>
            {{ form.as_table }}
          </table>
        </div>
        

        <br>
        
        <div>
          <div class="c-container--btn">
            <button type="submit" class="c-button">ログイン</button>
          </div>
        </div>
        
        <br>
        
        <input type="hidden" name="next" value={{ next }} />
        {% csrf_token %}
        
      </form>
    </div>
    <a href="{% url 'store:regist' %}">店舗ユーザー登録</a>
  </div>
{% endblock %}

templates/store/regist.html
{% extends 'base.html' %}

{% block content %}
  <div style="font-size: 4.5vw; padding: 5vw;">
    <div class="login-title">
      <ul class="list-inline">
        <li>店舗ユーザー登録</li>
      </ul>
    </div>
    <div>
      <form action="{% url 'store:regist' %}" method="POST">
        <div>
          <table style='margin: auto'>
            <tr>
              <th>{{ form.username.label }}:</th>
              <td>
                {{ form.username }} <br/>
                <span>{{ form.username.errors }}</span>
              </td>
            </tr>
            <tr>
              <th>{{ form.password1.label }}:</th>
              <td>
                {{ form.password1 }} <br/>
                <span>{{ form.password1.errors }}</span>
              </td>
            </tr>
            <tr>
              <th>{{ form.password2.label }}:</th>
              <td>
                {{ form.password2 }} <br/>
                <span>{{ form.password2.errors }}</span>
              </td>
            </tr>
          </table>
        </div>
        
        <br>
        
        <div>
          <div class="c-container--btn">
            <button type="submit" class="c-button">登録</button>
          </div>
        </div>
        
        <br>
        
        <input type="hidden" name="next" value={{ next }} />
        {% csrf_token %}
        
      </form>
    </div>
    <a href="{% url 'store:login' %}">店舗ログイン画面に戻る</a>
  </div>
{% endblock %}